# === Reference truth dataset ===
wb2_obs_url: gs://weatherbench2/datasets/era5/1959-2023_01_10-6h-240x121_equiangular_with_poles_conservative.zarr
forecast_days: 180
sample_stride: 5
#evaluation_checkpoint_id: 64
