# === Experiment specific ===
case: R4
local_store_path: "/pscratch/sd/n/nagarwal/ocn-only/${case}"
use_half_precision: false
log_tensorboard: true
logdir: "${local_store_path}/tensorboard/T7M"

# === Time Configuration Overrides ===
delta_t_model: 6h
delta_t_data: 6h
input_duration: 6h
target_lead_time: 6h

# === Base statistics directory ===
statistics_path: "/global/homes/n/nagarwal/graph-ufs/prototypes/ocn_only/statistics/ocn_only_7L_coarseTop/${delta_t_model}"

# === Norm Stats Path Override ===
norm_urls:
  atm:
    mean: "${statistics_path}/atm.fvstatistics.1993-2019/mean_by_level.zarr"
    std: "${statistics_path}/atm.fvstatistics.1993-2019/stddev_by_level.zarr"
    stddiff: "${statistics_path}/atm.fvstatistics.1993-2019/diffs_stddev_by_level.zarr"
  ocn:
    mean: "${statistics_path}/ocn.fvstatistics.1993-2019/mean_by_level.zarr"
    std: "${statistics_path}/ocn.fvstatistics.1993-2019/stddev_by_level.zarr"
    stddiff: "${statistics_path}/ocn.fvstatistics.1993-2019/diffs_stddev_by_level.zarr"
  ice: { mean: "", std: "", stddiff: "" }
  land: { mean: "", std: "", stddiff: "" }

# === Interface Configuration ===
interfaces:
  atm: [950, 1000]
  ocn: [0, 1, 21, 75, 120, 200, 350, 500]
  ice: []
  land: []

# === Training Hyperparameters ===
gnn_msg_steps: 12
latent_size: 256
lr_peak_value: 1e-4
num_epochs: 40

# === Noise injection ===
add_gauss_noise: true
noise_std_as_fraction: 0.1
gauss_noise_seed: 100

# === Evaluator Specific ===
wb2_obs_url: gs://weatherbench2/datasets/era5/1959-2023_01_10-6h-240x121_equiangular_with_poles_conservative.zarr
sample_stride: 5
