# === overrides ===
# Transforms have already been taken care of during preprocessing.
# This version operates on transformed (preprocessed) data, so 
# needs no transforms.

input_transforms: None
output_transforms: None
